#!/bin/sh

PYTHON_VERSION=${CONDA_PY:0:1}.${CONDA_PY:1:2}

if [ -z $PY3K ]; then
    PYTHON_LIBRARY=$PREFIX/lib/libpython2.7.so
    PYTHON_INCLUDE_DIR=$PREFIX/include/python2.7.so
else
    PYTHON_LIBRARY=$PREFIX/lib/libpython${PYTHON_VERSION}m.so
    PYTHON_INCLUDE_DIR=$PREFIX/include/python${PYTHON_VERSION}m
fi

BOOST_LIBRARY=$PREFIX/lib/libboost_python.so

ODLPP_SRCDIR=$SRC_DIR
ODLPP_BUILDDIR=$ODLPP_SRCDIR/build-py$PYTHON_VERSION
ODLPP_NUMPY_BUILDOPTS="-DPYTHON_NUMPY_INCLUDE_DIR=$PREFIX/lib/python$PYTHON_VERSION/site-packages/numpy/core/include"
ODLPP_PYTHON_BUILDOPTS="-DPYTHON_EXECUTABLE=$PYTHON -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR -DPYTHON_LIBRARY=$PYTHON_LIBRARY"
ODLPP_CUDA_BUILDOPTS="-DCUDA_TOOLKIT_ROOT_DIR=$CUDA_ROOT -DODL_CUDA_COMPUTE=$CUDA_COMPUTE"
ODLPP_BOOST_BUILDOPTS="-DBoost_PYTHON_LIBRARY_RELEASE=$BOOST_LIBRARY -DBoost_PYTHON_LIBRARY_DEBUG=$BOOST_LIBRARY"
ODLPP_CMAKEOPTS="$ODLPP_PYTHON_BUILDOPTS $ODLPP_NUMPY_BUILDOPTS $ODLPP_CUDA_BUILDOPTS $ODLPP_BOOST_BUILDOPTS $ODLPP_CC_BUILDOPTS"

ODLPP_CMAKE_COMMAND='cmake $ODLPP_CMAKEOPTS $ODLPP_SRCDIR'

mkdir -p $ODLPP_BUILDDIR && cd $ODLPP_BUILDDIR
eval $ODLPP_CMAKE_COMMAND
make pyinstall
cd -
