package:
    name: odlcuda
    version: "0.3.0"

source:
    git_url: https://github.com/odlgroup/odlcuda.git
    # TODO: this is for testing. Change to a version tag when done.
    git_rev: conda-build

build:
    number: 2
    script_env:
        - CUDA_ROOT
        - CUDA_COMPUTE

requirements:
    build:
        - python
        - nomkl
        - numpy >=1.9
        - future >=0.14
        - setuptools
        - boost

        # Make sure to run "conda config --append channels odlgroup" before building.
        - odl >=0.3.0

        # Compilers, needed for build only
        - gcc <5    # [linux]
        - llvm      # [osx]
        # ??? # [win]
    run:
        - python
        - nomkl
        - numpy >=1.9
        - future >=0.14
        - boost

        - odl >=0.3.0

test:
    imports:
        - odl

    commands:
        - python -c "import odl; odl.rn(5, impl='cuda').element()"

about:
    home: https://github.com/odlgroup/odlcuda
    license: GPLv3+
    license_file: LICENSE
    summary: "CUDA backend for ODL"

extra:
    maintainers:
        - Jonas Adler (@adler-j)
        - Holger Kohr (@kohr-h)
